on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  publish-docker-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: 27.5.1/py3.11.11/alpine3.21
            tags: |
              ghcr.io/${{ github.repository }}:27.5.1-py3.11.11-alpine3.21
              ghcr.io/${{ github.repository }}:27.5.1-py3.11.11-alpine
              ghcr.io/${{ github.repository }}:27.5.1-py3.11.11
              ghcr.io/${{ github.repository }}:27.5.1-py3.11-alpine3.21
              ghcr.io/${{ github.repository }}:27.5.1-py3.11-alpine
              ghcr.io/${{ github.repository }}:27.5.1-py3.11
              ghcr.io/${{ github.repository }}:27.5.1-py3-alpine3.21
              ghcr.io/${{ github.repository }}:27.5.1-py3-alpine
              ghcr.io/${{ github.repository }}:27.5.1-py3
              ghcr.io/${{ github.repository }}:27.5.1-alpine3.21
              ghcr.io/${{ github.repository }}:27.5.1-alpine
              ghcr.io/${{ github.repository }}:27.5.1
              ghcr.io/${{ github.repository }}:27.5-py3.11.11-alpine3.21
              ghcr.io/${{ github.repository }}:27.5-py3.11.11-alpine
              ghcr.io/${{ github.repository }}:27.5-py3.11.11
              ghcr.io/${{ github.repository }}:27.5-py3.11-alpine3.21
              ghcr.io/${{ github.repository }}:27.5-py3.11-alpine
              ghcr.io/${{ github.repository }}:27.5-py3.11
              ghcr.io/${{ github.repository }}:27.5-py3-alpine3.21
              ghcr.io/${{ github.repository }}:27.5-py3-alpine
              ghcr.io/${{ github.repository }}:27.5-py3
              ghcr.io/${{ github.repository }}:27.5-alpine3.21
              ghcr.io/${{ github.repository }}:27.5-alpine
              ghcr.io/${{ github.repository }}:27.5
              ghcr.io/${{ github.repository }}:27-py3.11.11-alpine3.21
              ghcr.io/${{ github.repository }}:27-py3.11.11-alpine
              ghcr.io/${{ github.repository }}:27-py3.11.11
              ghcr.io/${{ github.repository }}:27-py3.11-alpine3.21
              ghcr.io/${{ github.repository }}:27-py3.11-alpine
              ghcr.io/${{ github.repository }}:27-py3.11
              ghcr.io/${{ github.repository }}:27-py3-alpine3.21
              ghcr.io/${{ github.repository }}:27-py3-alpine
              ghcr.io/${{ github.repository }}:27-py3
              ghcr.io/${{ github.repository }}:27-alpine3.21
              ghcr.io/${{ github.repository }}:27-alpine
              ghcr.io/${{ github.repository }}:27
              ghcr.io/${{ github.repository }}:py3.11.11-alpine3.21
              ghcr.io/${{ github.repository }}:py3.11.11-alpine
              ghcr.io/${{ github.repository }}:py3.11.11
              ghcr.io/${{ github.repository }}:py3.11-alpine3.21
              ghcr.io/${{ github.repository }}:py3.11-alpine
              ghcr.io/${{ github.repository }}:py3.11
              ghcr.io/${{ github.repository }}:py3-alpine3.21
              ghcr.io/${{ github.repository }}:py3-alpine
              ghcr.io/${{ github.repository }}:py3
              ghcr.io/${{ github.repository }}:alpine3.21
              ghcr.io/${{ github.repository }}:alpine
              ghcr.io/${{ github.repository }}:latest
    permissions:
      packages: write
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
