on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  publish-docker-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: 27/py3.11
            tags: |
              ghcr.io/${{ github.repository }}:27.5-py3.11
              ghcr.io/${{ github.repository }}:27-py3.11
              ghcr.io/${{ github.repository }}:py3.11
          - context: 27/py3.12
            tags: |
              ghcr.io/${{ github.repository }}:27.5-py3.12
              ghcr.io/${{ github.repository }}:27-py3.12
              ghcr.io/${{ github.repository }}:py3.12
          - context: 27/py3.13
            tags: |
              ghcr.io/${{ github.repository }}:27.5-py3.13
              ghcr.io/${{ github.repository }}:27.5-py3
              ghcr.io/${{ github.repository }}:27.5
              ghcr.io/${{ github.repository }}:27-py3.13
              ghcr.io/${{ github.repository }}:27-py3
              ghcr.io/${{ github.repository }}:27
              ghcr.io/${{ github.repository }}:py3.13
              ghcr.io/${{ github.repository }}:py3
              ghcr.io/${{ github.repository }}:latest
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          tags: ${{ matrix.tags }}
